### PR TITLE
More material-like dark theme

### PR DESCRIPTION
**Pull request by Skehmatics**
Use a more neutral color scheme for the dark mode. More representative of Material Design's Dark spec

### CODE REVIEW

**Comment by elxa** [comment]
**Running dconf-editor with GTK_DEBUG=interactive**

![]
(http://i.imgur.com/C05Ka6q.png)

![]
(http://i.imgur.com/YJ8jkpc.png)

**Comment by nana-4** [comment]
Please accept my apologies for my long silence. But I dare to do this way because I thought `Blue Grey` is easy on the eyes than `Grey`. So, I can't merge it.

**Comment by Skehmatics** [comment]
No problem! Keep up the great work

**Comment by nana-4** [comment]
Thanks :smiley:

**Pull request closed without merging**
