### PR TITLE
feat(change_color.sh): script to generate theme with custom color

### PR DESCRIPTION
**Pull request by actionless**
To test in `bash`:

```bash
$ ./change_color.sh -o my-test-theme <(echo -e "BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n")
```

To test in `fish`:

```fish
$ ./change_color.sh -o my-test-theme (echo -e "BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n" | psub)
```

### CODE REVIEW

**Comment by actionless** [comment]
good, i've almost done with oomox side, soon gonna do a release or RC

**Comment by nana-4** [comment]
@actionless 
I'm sorry for the late reply... And thank you for your hard work! So fantastic! It looks VERY good more than I expected. I'm going to write about oomox on the README later. :)

btw, I noticed a small issue with oomox.

| _vanilla_ Flat-Plat | Flat-Plat with Numix color scheme |
| --- | --- |
| image | image |

As [the material design guideline](https://material.io/guidelines/style/color.html#color-color-system) recommends, Flat-Plat has two accent colors, **primary color** and **secondary color**.

However, since oomox currently uses them as one color, `checkbox`, `swith`, `slider`, etc are almost invisible when the background is selected. So I propose to make both *primary color* and *secondary color* configurable. But if it is difficult for some reasons please do not hesitate to discard this proposal. 😃

**Comment by actionless** [comment]
just set `ACCENT_BG` and `SEL_BG` of your theme to different values

**Comment by nana-4** [comment]
@actionless 
oops. I'm sorry for my mistake! I didn't check it properly. :/

> btw feel free to submit some colorschemes to oomox/colors

Thanks! I'd like to send you a PR If I have some time and find nice color schemes. :)

**Pull request merged**
