### PR TITLE
Support both pre- and post- Gtk3.20

### PR DESCRIPTION
**Pull request by Salamandar**
Well, it's a copy-paste from the old commit, but still…

### CODE REVIEW

**Comment by nana-4** [comment]
Why is it necessary to do this?
Are there any apps that is not displayed correctly if we don't do this?

**Comment by cthbleachbit** [comment]
Thr gtk 3.20 theme won't render correctly on lower gtk versions (not a problem for Gentoo and Archlinux but surely a problem for other distributions)

**Comment by Salamandar** [comment]
Yes. The 3.20 version is not backwards-compatible for themes. Some say they should have named it Gtk4…

**Comment by nana-4** [comment]
Sorry for the neglect. I couldn’t understand the necessity of this. This might convenient indeed, but there is a problem. That's because GNOME Shell doesn't support multiple versioned themes at the moment. It may lead to confusion or danger for GNOME Shell users. Also it will increase the maintenance burden. Therefore, I cannot accept this at least until GNOME Shell supports multiple versioned themes.

**Pull request closed without merging**
