### PR TITLE
changed undershoots with linear gradients

### PR DESCRIPTION
**Pull request by Salamandar**
I'm pretty sure there are ways to make prettier shadows than that, but it seems okay to me !

### CODE REVIEW

**Comment by Salamandar** [comment]
I created a grey colour that seemed the best looking for me :)

**Comment by nana-4** [comment]
shadows
I don't really like the window's edge becomes ambiguous by the outer and inner shadows.

Sorry, but I can't merge this for my taste.

**Comment by Salamandar** [comment]
Hmm, i see what you mean. There can be a way to remove this with some margins. What do you think ?

**Comment by nana-4** [comment]
Sorry, but I cannot imagine well what you mean.
Why margins? When some margins is inserted, becomes meaningless to be shadows, I think...

**Comment by Salamandar** [comment]
I think i misunderstood your comment, i thought you didn't like the corner. 
Well of course it seems like inner shadows, but that's the point, right ? It shows the "overscrolling" like in sublime text, for instance.

**Pull request closed without merging**
