### PR TITLE
feat(gtk2, gtk3: render-assets): use `parallel` if installed

### PR DESCRIPTION
**Pull request by actionless**
Sequentially:
 134.22 seconds

In parallel:
 92.91 seconds

### CODE REVIEW

**Comment by nana-4** [comment]
Great. Thanks!

**Comment by actionless** [comment]
btw i also noticed what for some reason optipng disabled for gtk3 (but not for gtk2)

```patch
diff --git a/src/gtk-3.0/gtk-common/render-asset.sh b/src/gtk-3.0/gtk-common/render-asset.sh
index 6814f15..d17fbbe 100755
--- a/src/gtk-3.0/gtk-common/render-asset.sh
+++ b/src/gtk-3.0/gtk-common/render-asset.sh
@@ -15,8 +15,8 @@ else
     echo Rendering $ASSETS_DIR/$i.png
     $INKSCAPE --export-id=$i \
               --export-id-only \
-              --export-png=$ASSETS_DIR/$i.png $SRC_FILE >/dev/null #\
-    # && $OPTIPNG -o7 --quiet $ASSETS_DIR/$i.png
+              --export-png=$ASSETS_DIR/$i.png $SRC_FILE >/dev/null \
+    && $OPTIPNG -o7 --quiet $ASSETS_DIR/$i.png
 fi
 if [ -f $ASSETS_DIR/$i@2.png ]; then
     echo $ASSETS_DIR/$i@2.png exists.
@@ -26,8 +26,8 @@ else
     $INKSCAPE --export-id=$i \
               --export-dpi=192 \
               --export-id-only \
-              --export-png=$ASSETS_DIR/$i@2.png $SRC_FILE >/dev/null #\
-    # && $OPTIPNG -o7 --quiet $ASSETS_DIR/$i@2.png
+              --export-png=$ASSETS_DIR/$i@2.png $SRC_FILE >/dev/null \
+    && $OPTIPNG -o7 --quiet $ASSETS_DIR/$i@2.png
 fi

 exit 0
```

**Comment by nana-4** [comment]
`render-assets.sh` scripts just picked up from the upstream Adwaita. And I did not change anything. see:
- https://github.com/GNOME/gtk/blob/master/gtk/theme/Adwaita/render-assets.sh
- https://github.com/GNOME/gnome-themes-standard/blob/master/themes/Adwaita/gtk-2.0/render-assets.sh

**Comment by actionless** [comment]
i would suggest to put some consistency into that

**Comment by nana-4** [comment]
indeed. So let's enable optipng for gtk3.

**Pull request merged**
