### PR TITLE
integrate scripts and destination folder selection

### PR DESCRIPTION
**Pull request by cthbleachbit**
Current script structure made installation to custom directory impossible, which is required during packaging. So I revised the installation scripts. Also please consider migrate to Makefile.

### CODE REVIEW

**Comment by nana-4** [comment]
Thanks but, your script has not properly renamed files or directories.
For example, to properly install the `Flat-Plat-light`, we must rename `gtk-light.css` to `gtk.css` currently.

I am not familiar with programming or packaging, so I don't know if the current method is good.
I tried to challenge the Makefile, but I was shamefully frustrated. 😕
I would be glad if someone suggests a better way or sends a PR...

**Comment by nana-4** [comment]
I tried rewriting the script to **properly** install themes while referring to your script. (thanks again!) How is this?

**Comment by cthbleachbit** [comment]
Looking pretty good.

**Comment by cthbleachbit** [comment]
i'll try to write a Makefile for this.

**Comment by cthbleachbit** [comment]
Plus, here's my email `cth451@gmail.com`
If you could, pls send me a email about how you "build" the `css` out of `scss`.

It'll be better if you exclude the generated `css` out of repository, Whenever an user wants to install them, the user will construct css from scss locally with `ruby-saas` as I'll specify in Makefile.

**Comment by nana-4** [comment]
> how you "build" the css out of scss.

Basically it is as written in [HACKING](https://github.com/nana-4/Flat-Plat/blob/master/HACKING).
After installing `rubygems`, move to `Flat-Plat` repo directory on terminal and run `gem install bundle && bundle install`. If you edit `.scss` files and run `./parse-sass.sh`, it will automatically load the subdirectories and generate CSSs.

By the way, I don't think it would be better to exclude CSS out of repository. To reduce the burden on users, I think it is better to bundle them from the beginning. It will also save installation time. For example, default [Adwaita](https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita) also includes the generated CSS.

**Pull request closed without merging**
